# Generated by Django 3.2.7 on 2021-11-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211110_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
