# Generated by Django 3.2.7 on 2021-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_points',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
