# Generated by Django 3.2.7 on 2021-11-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_flag',
            old_name='flag',
            new_name='flag_object',
        ),
    ]
